# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - sofa-society-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        working-directory: ./medusa-store
        run: |
          npm ci
          npm run build --if-present

      - name: Prepare deployment package
        working-directory: ./medusa-store
        run: |
          mkdir -p deploy
          cp -r node_modules public .medusa package.json package-lock.json medusa-config.ts start-server.js deploy/
          cd deploy
          zip -r ../deploy.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./medusa-store/deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B7065FA0DD92426E8564538BDD952F06 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E1CF36606A4A451083A0C2FA583CA911 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E05F49DE6EF34BF5BBB03D51F1E82FB1 }}

      - name: Configure App Settings to disable Oryx build
        uses: azure/appservice-settings@v1
        with:
          app-name: 'sofa-society-backend'
          app-settings-json: '[{"name":"SCM_DO_BUILD_DURING_DEPLOYMENT","value":"false"},{"name":"ENABLE_ORYX_BUILD","value":"false"},{"name":"DISABLE_MEDUSA_ADMIN","value":"true"}]'

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sofa-society-backend'
          slot-name: 'Production'
          package: deploy.zip
        env:
          SCM_DO_BUILD_DURING_DEPLOYMENT: false
          ENABLE_ORYX_BUILD: false
          